name: Publish to Firebase Distribution

on:
  push:
    branches:
      - 'feature/ci-cd'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Touch local properties
        run: touch local.properties
      - name: Add Api Key
        run: echo "auth_url=\"\"" >> local.properties
      - run: chmod +x ./gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # 2
      - name: Generate APK
        run: ./gradlew assembleRelease
      # 3
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

#  deploy-firebase:
#    # 1
#    needs: [ build ]
#    runs-on: ubuntu-latest
#    steps:
#      # 2
#      - uses: actions/download-artifact@master
#        with:
#          name: app-debug.apk
#      #3
#      - name: upload artifact to Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{secrets.FIREBASE_APP_ID}}
#          token: ${{secrets.FIREBASE_TOKEN}}
#          groups: QA
#          file: app-debug.apk